# Generated by Django 3.0.8 on 2020-07-20 09:37

from django.db import migrations, models
import django.db.models.deletion
import question.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False, verbose_name='board_id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('regDate', models.DateTimeField(auto_now_add=True, verbose_name='regDate')),
                ('updDate', models.DateTimeField(auto_now=True, verbose_name='updDate')),
            ],
        ),
        migrations.CreateModel(
            name='AttFile',
            fields=[
                ('attfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', question.fields.ThumbnailImageField(blank=True, default=None, null=True, upload_to='board/image/%y/%m')),
                ('regDate', models.DateTimeField(auto_now_add=True, verbose_name='date register')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Board')),
            ],
        ),
    ]
