# Generated by Django 3.0.8 on 2020-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('user_id', models.CharField(max_length=64, verbose_name='사용자명')),
                ('user_pw', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('user_type', models.IntegerField()),
            ],
        ),
    ]
