# Generated by Django 3.0.8 on 2020-07-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0002_remove_t_list_field_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False, verbose_name='content_id')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
                ('img', models.ImageField(blank=True, upload_to='./ans_img/% Y/% m/% d/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('content_type', models.IntegerField(default=0)),
                ('reply_chk', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Accounts')),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
