# Generated by Django 3.0.8 on 2020-07-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='account',
            new_name='user_id',
        ),
    ]
