# Generated by Django 3.0.8 on 2020-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200723_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='img',
            field=models.ImageField(blank=True, upload_to='./ans_img/% Y/% m/% d/'),
        ),
    ]
